-- AlterTable
ALTER TABLE `budgets` ADD COLUMN `date_type` ENUM('DAILY', 'WEEKLY', 'MONTHLY') NOT NULL DEFAULT 'DAILY',
    ADD COLUMN `month` INTEGER NULL,
    ADD COLUMN `spend` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `week` INTEGER NULL,
    ADD COLUMN `year` INTEGER NULL,
    MODIFY `end_date` DATETIME(3) NULL,
    MODIFY `start_date` DATETIME(3) NULL;
