-- CreateTable
CREATE TABLE `walmart_attributed_purchases` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `brandId` INTEGER NOT NULL,
    `date` DATETIME(0) NULL,
    `campaignId` INTEGER NULL,
    `adGroupId` INTEGER NULL,
    `advertisedItemId` INTEGER NULL,
    `attributedOrders3days` INTEGER NULL,
    `attributedOrders14days` INTEGER NULL,
    `attributedOrders30days` INTEGER NULL,
    `attributionType` VARCHAR(50) NULL,
    `ntbOrders3day` INTEGER NULL,
    `ntbOrders14days` INTEGER NULL,
    `ntbOrders30days` INTEGER NULL,
    `ntbRevenue3days` DOUBLE NULL,
    `ntbRevenue14days` DOUBLE NULL,
    `ntbRevenue30days` DOUBLE NULL,
    `ntbUnits3days` INTEGER NULL,
    `ntbUnits14days` INTEGER NULL,
    `ntbUnits30days` INTEGER NULL,
    `purchasedItemId` INTEGER NULL,
    `purchasedItemName` VARCHAR(512) NULL,
    `totalSales3days` DOUBLE NULL,
    `totalSales14days` DOUBLE NULL,
    `totalSales30days` DOUBLE NULL,
    `totalUnits3days` INTEGER NULL,
    `totalUnits14days` INTEGER NULL,
    `totalUnits30day` INTEGER NULL,

    INDEX `walmart_page_type_adGroupId_index`(`adGroupId`),
    INDEX `walmart_page_type_brand_idx`(`brandId`),
    INDEX `walmart_page_type_campaignId_index`(`campaignId`),
    INDEX `walmart_page_type_date_index`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
