-- CreateTable
CREATE TABLE `walmart_placement` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `brandId` INTEGER NOT NULL,
    `date` DATETIME(0) NULL,
    `campaignId` INTEGER NOT NULL,
    `adGroupId` INTEGER NOT NULL,
    `ntbUnits3Days` INTEGER NULL,
    `ntbOrders3Days` INTEGER NULL,
    `ntbRevenue3Days` INTEGER NULL,
    `ntbUnits14Days` INTEGER NULL,
    `ntbOrders14Days` INTEGER NULL,
    `ntbRevenue14Days` INTEGER NULL,
    `ntbUnits30Days` INTEGER NULL,
    `ntbOrders30Days` INTEGER NULL,
    `ntbRevenue30Days` INTEGER NULL,
    `adSpend` INTEGER NULL,
    `numAdsShown` INTEGER NULL,
    `numAdsClicks` INTEGER NULL,
    `attributedOrders3Days` INTEGER NULL,
    `attributedOrders14Days` INTEGER NULL,
    `attributedOrders30Days` INTEGER NULL,
    `attributedUnits3Days` INTEGER NULL,
    `attributedUnits14Days` INTEGER NULL,
    `attributedUnits30Days` INTEGER NULL,
    `directAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `placement` VARCHAR(50) NULL,

    INDEX `walmart_placement_adGroupId_index`(`adGroupId`),
    INDEX `walmart_placement_brand_idx`(`brandId`),
    INDEX `walmart_placement_campaignId_index`(`campaignId`),
    INDEX `walmart_placement_date_index`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `walmart_platform` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `brandId` INTEGER NOT NULL,
    `date` DATETIME(0) NULL,
    `campaignId` INTEGER NOT NULL,
    `adGroupId` INTEGER NOT NULL,
    `ntbUnits3Days` INTEGER NULL,
    `ntbOrders3Days` INTEGER NULL,
    `ntbRevenue3Days` INTEGER NULL,
    `ntbUnits14Days` INTEGER NULL,
    `ntbOrders14Days` INTEGER NULL,
    `ntbRevenue14Days` INTEGER NULL,
    `ntbUnits30Days` INTEGER NULL,
    `ntbOrders30Days` INTEGER NULL,
    `ntbRevenue30Days` INTEGER NULL,
    `adSpend` INTEGER NULL,
    `numAdsShown` INTEGER NULL,
    `numAdsClicks` INTEGER NULL,
    `attributedOrders3Days` INTEGER NULL,
    `attributedOrders14Days` INTEGER NULL,
    `attributedOrders30Days` INTEGER NULL,
    `attributedUnits3Days` INTEGER NULL,
    `attributedUnits14Days` INTEGER NULL,
    `attributedUnits30Days` INTEGER NULL,
    `directAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `platform` VARCHAR(50) NULL,

    INDEX `walmart_platform_adGroupId_index`(`adGroupId`),
    INDEX `walmart_platform_brand_idx`(`brandId`),
    INDEX `walmart_platform_campaignId_index`(`campaignId`),
    INDEX `walmart_platform_date_index`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `walmart_page_type` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `brandId` INTEGER NOT NULL,
    `date` DATETIME(0) NULL,
    `campaignId` INTEGER NOT NULL,
    `adGroupId` INTEGER NOT NULL,
    `ntbUnits3Days` INTEGER NULL,
    `ntbOrders3Days` INTEGER NULL,
    `ntbRevenue3Days` INTEGER NULL,
    `ntbUnits14Days` INTEGER NULL,
    `ntbOrders14Days` INTEGER NULL,
    `ntbRevenue14Days` INTEGER NULL,
    `ntbUnits30Days` INTEGER NULL,
    `ntbOrders30Days` INTEGER NULL,
    `ntbRevenue30Days` INTEGER NULL,
    `adSpend` INTEGER NULL,
    `numAdsShown` INTEGER NULL,
    `numAdsClicks` INTEGER NULL,
    `attributedOrders3Days` INTEGER NULL,
    `attributedOrders14Days` INTEGER NULL,
    `attributedOrders30Days` INTEGER NULL,
    `attributedUnits3Days` INTEGER NULL,
    `attributedUnits14Days` INTEGER NULL,
    `attributedUnits30Days` INTEGER NULL,
    `directAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `directAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `advertisedSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `brandAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `relatedAttributedSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales3days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales14days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `otherSkuSales30days` DECIMAL(15, 3) NULL DEFAULT 0.000,
    `pageType` VARCHAR(50) NULL,

    INDEX `walmart_page_type_adGroupId_index`(`adGroupId`),
    INDEX `walmart_page_type_brand_idx`(`brandId`),
    INDEX `walmart_page_type_campaignId_index`(`campaignId`),
    INDEX `walmart_page_type_date_index`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
